version: "3.8"

services:
  db:
    image: mariadb:10.11
    container_name: laboratoriodedu_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laboratoriodedu
      MYSQL_USER: du_user
      MYSQL_PASSWORD: du_pass
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:php8.2-apache
    container_name: laboratoriodedu_app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: du_user
      WORDPRESS_DB_PASSWORD: du_pass
      WORDPRESS_DB_NAME: laboratoriodedu
      WORDPRESS_DEBUG: 1
      WORDPRESS_DEBUG_DISPLAY: 0
      WORDPRESS_DEBUG_LOG: 1
    volumes:
      - ./wp-content:/var/www/html/wp-content

volumes:
  db_data:
